/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentTicketsRouteImport } from './routes/_authenticated.student.tickets'
import { Route as AuthenticatedStudentNoticesRouteImport } from './routes/_authenticated.student.notices'
import { Route as AuthenticatedStudentChatRouteImport } from './routes/_authenticated.student.chat'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated.admin.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentTicketsRoute =
  AuthenticatedStudentTicketsRouteImport.update({
    id: '/student/tickets',
    path: '/student/tickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentNoticesRoute =
  AuthenticatedStudentNoticesRouteImport.update({
    id: '/student/notices',
    path: '/student/notices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentChatRoute =
  AuthenticatedStudentChatRouteImport.update({
    id: '/student/chat',
    path: '/student/chat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/student/chat': typeof AuthenticatedStudentChatRoute
  '/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/student/tickets': typeof AuthenticatedStudentTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/student/chat': typeof AuthenticatedStudentChatRoute
  '/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/student/tickets': typeof AuthenticatedStudentTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/student/chat': typeof AuthenticatedStudentChatRoute
  '/_authenticated/student/notices': typeof AuthenticatedStudentNoticesRoute
  '/_authenticated/student/tickets': typeof AuthenticatedStudentTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/admin/chat'
    | '/admin/dashboard'
    | '/student/chat'
    | '/student/notices'
    | '/student/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/admin/chat'
    | '/admin/dashboard'
    | '/student/chat'
    | '/student/notices'
    | '/student/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/student/chat'
    | '/_authenticated/student/notices'
    | '/_authenticated/student/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/tickets': {
      id: '/_authenticated/student/tickets'
      path: '/student/tickets'
      fullPath: '/student/tickets'
      preLoaderRoute: typeof AuthenticatedStudentTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/notices': {
      id: '/_authenticated/student/notices'
      path: '/student/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof AuthenticatedStudentNoticesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/chat': {
      id: '/_authenticated/student/chat'
      path: '/student/chat'
      fullPath: '/student/chat'
      preLoaderRoute: typeof AuthenticatedStudentChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedStudentChatRoute: typeof AuthenticatedStudentChatRoute
  AuthenticatedStudentNoticesRoute: typeof AuthenticatedStudentNoticesRoute
  AuthenticatedStudentTicketsRoute: typeof AuthenticatedStudentTicketsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedStudentChatRoute: AuthenticatedStudentChatRoute,
  AuthenticatedStudentNoticesRoute: AuthenticatedStudentNoticesRoute,
  AuthenticatedStudentTicketsRoute: AuthenticatedStudentTicketsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
