import re
import hashlib
import secrets
import logging
from fastapi import APIRouter, HTTPException, status, Depends
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel, EmailStr, field_validator
from typing import Optional
from firebase_admin import auth as firebase_auth

from app.database import get_db
from app.models.db_models import User
from app.services.security import verify_admin_clearance  # 🛡️ Structural dependency guard

router = APIRouter(prefix="/auth", tags=["Unified Identity & Access Management"])

# ==============================================================================
# 🔑 CRYPTOGRAPHIC PASSWORD SECURITY UTILITIES (ZERO ENVIRONMENT DEPENDENCY)
# ==============================================================================
def hash_password(password: str) -> str:
    """Hashes a password using built-in secure PBKDF2-HMAC-SHA256 with a unique salt."""
    salt = secrets.token_hex(16)
    key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt.encode('utf-8'), 100000)
    return f"{salt}${key.hex()}"

def verify_password(password: str, hashed_password: str) -> bool:
    """Verifies a password against an existing PBKDF2 token hash string."""
    if "$" not in hashed_password or hashed_password == "OAUTH_EXTERNAL_MANAGED_IDENTITY":
        return False
    salt, hex_key = hashed_password.split("$", 1)
    key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt.encode('utf-8'), 100000)
    return key.hex() == hex_key


# ==============================================================================
# 📊 AUTHENTICATION DATA TRANSFER SCHEMAS
# ==============================================================================
class TokenExchangePayload(BaseModel):
    id_token: str  # The raw cryptographic secure JWT token emitted by Firebase on the UI

class UserIdentityProfileResponse(BaseModel):
    uid: Optional[str]
    email: str
    name: str
    role: str
    redirect_target: str  # Tells the frontend router precisely where to redirect the user
    is_active: bool

class PromoteUserPayload(BaseModel):
    target_email: EmailStr
    target_role: str = "admin"

class AdminCreationPayload(BaseModel):
    full_name: str
    email: EmailStr
    username: str
    password: str

    @field_validator("username")
    @classmethod
    def enforce_username_matrix_rules(cls, v: str) -> str:
        """Enforces enterprise alphanumeric security rules (FR-09 Alignment)."""
        username_regex = r"^[a-z][a-z0-9_.]{3,19}$"
        if not re.match(username_regex, v):
            raise ValueError(
                "Username must start with a lowercase letter, contain only a-z, 0-9, underscores, or periods, and be between 4 and 20 characters."
            )
        return v

class AdminLoginPayload(BaseModel):
    username: str  # This string accepts either the alphanumeric username OR the official email address safely
    password: str

class AdminLoginResponse(BaseModel):
    uid: Optional[str]
    email: str
    name: str
    role: str
    custom_token: str  # Firebase Custom Token generated by the Admin SDK for client mirroring
    redirect_target: str


# ==============================================================================
# 🔄 ENDPOINT 1: THE UNIFIED ROLE-DISCOVERY IDENTITY SYNC (STUDENT GATEWAY)
# ==============================================================================
@router.post("/sync", response_model=UserIdentityProfileResponse)
async def synchronize_and_discover_user_role(
    payload: TokenExchangePayload,
    db: AsyncSession = Depends(get_db)
):
    """
    🔐 Hybrid Single-Sign-On Identity Sync Gateway
    Intercepts short-lived cloud provider identity tokens, validates signatures statelessly, 
    auto-provisions new users as students, and returns structural portal redirection targets.
    """
    try:
        # 1. Verify the cryptographic token signature via Firebase Admin SDK
        decoded_token = firebase_auth.verify_id_token(payload.id_token)
        fb_uid = decoded_token.get("uid")
        fb_email = decoded_token.get("email") or decoded_token.get("claims", {}).get("email")
        fb_name = decoded_token.get("name", fb_email.split("@")[0] if fb_email else "Campus User")
        
    except Exception as token_err:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Identity verification failed. Secure token rejected: {str(token_err)}"
        )

    # 2. Query the relational database to find the user profile via unique indexed identifiers
    try:
        user_query = select(User).where((User.firebase_uid == fb_uid) | (User.email == fb_email))
        query_result = await db.execute(user_query)
        existing_user = query_result.scalar_one_or_none()

        # 3. Auto-Provisioning Loop: If the user is completely new, create them as a student profile automatically
        if not existing_user:
            if not fb_email:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Identity provider token configuration error: Email attribute missing."
                )
            existing_user = User(
                email=fb_email,
                hashed_password="OAUTH_EXTERNAL_MANAGED_IDENTITY",  # Handled safely via token provider
                name=fb_name,
                role="student",  # 🟢 Safe default baseline authorization tier
                username=None,   # Baseline students do not possess alphanumeric usernames
                firebase_uid=fb_uid,
                is_active=True
            )
            db.add(existing_user)
            await db.commit()
            await db.refresh(existing_user)
            print(f"👤 [IDENTITY AUTO-PROVISIONED] Created profile row for {fb_email} as 'student'.")
            
        # 4. Data Repair Sync: If user existed via local credentials but lacks a cloud anchor token, link it now
        elif not existing_user.firebase_uid:
            existing_user.firebase_uid = fb_uid
            db.add(existing_user)
            await db.commit()
            await db.refresh(existing_user)

        if not existing_user.is_active:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="This campus account infrastructure profile has been administratively deactivated."
            )

        # 5. Dynamic Redirection Mapping Node
        redirect_map = {
            "admin": "/admin/dashboard",
            "helpdesk": "/admin/dashboard",
            "faculty": "/admin/dashboard",
            "student": "/student/chat"
        }
        target_route = redirect_map.get(existing_user.role, "/student/chat")

        return {
            "uid": existing_user.firebase_uid,
            "email": existing_user.email,
            "name": existing_user.name,
            "role": existing_user.role,
            "redirect_target": target_route,
            "is_active": existing_user.is_active
        }

    except HTTPException:
        raise
    except Exception as system_fault:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal database mapping fault during synchronization: {str(system_fault)}"
        )


# ==============================================================================
# 🏢 ENDPOINT 2: SECURE USERNAME/PASSWORD ADMINISTRATIVE LOGIN GATEWAY
# ==============================================================================
@router.post("/admin-login", response_model=AdminLoginResponse)
async def administrative_credentials_login(
    payload: AdminLoginPayload,
    db: AsyncSession = Depends(get_db)
):
    """
    🔐 Hardened Administrative Entrance Gateway
    Accepts both unique alphanumeric username strings or institutional email coordinates,
    compares PBKDF2 hashes safely, and mints an isolated session cookie custom token response.
    """
    # 1. DUAL LOOKUP Matrix: Check if the string matches EITHER username column OR official email column
    query = select(User).where((User.username == payload.username) | (User.email == payload.username))
    result = await db.execute(query)
    admin_user = result.scalar_one_or_none()

    if not admin_user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Access Denied: Invalid administrative credentials configuration."
        )

    # 2. Verify cryptographically hashed security key strings
    if not verify_password(payload.password, admin_user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Access Denied: Invalid administrative credentials configuration."
        )

    if not admin_user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This administrative workspace context profile has been deactivated."
        )

    # 3. Defensive Gate: Ensure standard baseline student roles can never hijack this gateway
    if admin_user.role not in ["admin", "helpdesk", "faculty"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Security Violation: Insufficient role credentials clearance mapping."
        )

    try:
        # 4. 🟢 FIXED: Attach explicit custom developer claims context directly to token allocation profiles
        developer_claims = {
            "email": admin_user.email,
            "role": admin_user.role
        }
        custom_token = firebase_auth.create_custom_token(admin_user.firebase_uid, developer_claims)
        custom_token_str = custom_token.decode("utf-8") if isinstance(custom_token, bytes) else custom_token
    except Exception as token_err:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Identity pipeline critical error: Failed to mint session context: {str(token_err)}"
        )

    redirect_map = {
        "admin": "/admin/dashboard",
        "helpdesk": "/admin/dashboard",
        "faculty": "/admin/dashboard"
    }

    return {
        "uid": admin_user.firebase_uid,
        "email": admin_user.email,
        "name": admin_user.name,
        "role": admin_user.role,
        "custom_token": custom_token_str,
        "redirect_target": redirect_map.get(admin_user.role, "/admin/dashboard")
    }


# ==============================================================================
# ➕ ENDPOINT 3: ISOLATED ADMINISTRATIVE ACCOUNT PROVISIONING 
# ==============================================================================
@router.post("/create-admin", status_code=status.HTTP_201_CREATED)
async def create_new_administrative_user(
    payload: AdminCreationPayload,
    current_admin: dict = Depends(verify_admin_clearance),  # 🛡️ Protected by strict security dependency checks
    db: AsyncSession = Depends(get_db)
):
    """
    👑 Programmatic Administrative Provisioning Core
    Allows an authenticated administrator to securely register new managers.
    Bypasses public onboarding endpoints entirely by running requests directly via the Firebase Admin SDK.
    """
    # 1. Check database constraint lines to enforce global uniqueness
    username_check = await db.execute(select(User).where(User.username == payload.username))
    if username_check.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"The administrative username '{payload.username}' is already allocated inside system records."
        )

    email_check = await db.execute(select(User).where(User.email == payload.email))
    if email_check.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"The institutional address '{payload.email}' is already mapped to an active profile."
        )

    try:
        # 2. Programmatically provision user account inside central Firebase cloud tenancy
        fb_user = firebase_auth.create_user(
            email=payload.email,
            password=payload.password,
            display_name=payload.full_name
        )
        fb_uid = fb_user.uid
    except Exception as cloud_err:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Cloud infrastructure identity allocation exception dropped: {str(cloud_err)}"
        )

    try:
        # 3. Compile and insert matching record row directly into local user table
        new_admin = User(
            email=payload.email,
            hashed_password=hash_password(payload.password),
            name=payload.full_name,
            role="admin",
            username=payload.username,
            firebase_uid=fb_uid,
            is_active=True
        )
        db.add(new_admin)
        await db.commit()
        
        print(f"👑 [ADMIN PROVISIONED] New operator '{payload.username}' generated by {current_admin.get('email')}.")
        return {
            "success": True, 
            "message": f"Administrative operator profile '{payload.username}' successfully registered."
        }
    except Exception as db_err:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Relational persistent storage write block failed: {str(db_err)}"
        )


# ==============================================================================
# 🔼 ENDPOINT 4: ADMINISTRATIVE ROLE PROMOTION ELEVATION
# ==============================================================================
@router.post("/promote", status_code=status.HTTP_200_OK)
async def elevate_user_access_clearance(
    payload: PromoteUserPayload,
    current_admin: dict = Depends(verify_admin_clearance),  # 🛡️ Locked behind strict admin route security checks
    db: AsyncSession = Depends(get_db)
):
    """
    🔼 Administrative Access Escalation Endpoint
    Allows authorized administrators to update any student's role profile rows 
    to 'admin' status instantly via structural target parameter inputs.
    """
    if payload.target_role not in ["admin", "student", "helpdesk", "faculty"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Target promotion value '{payload.target_role}' is not a recognized campus role archetype."
        )

    # Search for the target user profile record by email address
    user_lookup = select(User).where(User.email == payload.target_email)
    lookup_result = await db.execute(user_lookup)
    target_user = lookup_result.scalar_one_or_none()

    if not target_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Operation aborted: No user profile row exists matching address '{payload.target_email}'."
        )

    # Guard: Prevent self-demotion anomalies
    if target_user.email == current_admin.get("email") and payload.target_role != "admin":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Security Violations: An administrator cannot strip away their own structural clearance codes."
        )

    try:
        old_role = target_user.role
        target_user.role = payload.target_role
        
        db.add(target_user)
        await db.commit()
        
        print(f"👑 [ACCESS UPGRADED] {target_user.email} changed roles from '{old_role}' to '{payload.target_role}' by admin operator {current_admin.get('email')}.")
        
        return {
            "success": True,
            "message": f"Account profile authorization updated completely.",
            "target_user_email": target_user.email,
            "previous_clearance": old_role,
            "assigned_clearance": target_user.role,
            "authorizing_operator": current_admin.get("email")
        }

    except Exception as write_fault:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to modify target authorization parameter settings: {str(write_fault)}"
        )