import re
import hashlib
import secrets
import logging
import datetime
from fastapi import APIRouter, HTTPException, status, Depends
from sqlalchemy import select, update, text
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel, EmailStr, field_validator
from typing import Optional
from firebase_admin import auth as firebase_auth

from app.database import get_db
from app.models.db_models import User
from app.services.security import verify_admin_clearance  # 🛡️ Protected administrative access guard

router = APIRouter(prefix="/auth", tags=["Unified Identity & Access Management"])

# ==============================================================================
# 🔑 CRYPTOGRAPHIC PASSWORD SECURITY UTILITIES (ZERO ENVIRONMENT DEPENDENCY)
# ==============================================================================
def hash_password(password: str) -> str:
    """Hashes a password using built-in secure PBKDF2-HMAC-SHA256 with a unique salt."""
    salt = secrets.token_hex(16)
    key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt.encode('utf-8'), 100000)
    return f"{salt}${key.hex()}"

def verify_password(password: str, hashed_password: str) -> bool:
    """Verifies a password against an existing PBKDF2 token hash string."""
    if "$" not in hashed_password or hashed_password == "OAUTH_EXTERNAL_MANAGED_IDENTITY":
        return False
    salt, hex_key = hashed_password.split("$", 1)
    key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt.encode('utf-8'), 100000)
    return key.hex() == hex_key


# ==============================================================================
# 📊 AUTHENTICATION DATA TRANSFER SCHEMAS
# ==============================================================================
class TokenExchangePayload(BaseModel):
    id_token: str  # The raw cryptographic secure JWT token emitted by Firebase on the UI

class UserIdentityProfileResponse(BaseModel):
    uid: Optional[str]
    email: str
    name: str
    role: str
    redirect_target: str  # Tells the frontend router precisely where to redirect the user
    is_active: bool

class PromoteUserPayload(BaseModel):
    target_email: EmailStr
    target_role: str = "admin"

class AdminLoginPayload(BaseModel):
    username: str  # This string accepts either the alphanumeric username OR the official email address safely
    password: str

class AdminLoginResponse(BaseModel):
    uid: Optional[str]
    email: str
    name: str
    role: str
    custom_token: str  # Firebase Custom Token generated by the Admin SDK for client mirroring
    redirect_target: str


# ==============================================================================
# 🔄 ENDPOINT 1: THE UNIFIED ROLE-DISCOVERY IDENTITY SYNC (STUDENT GATEWAY)
# ==============================================================================
@router.post("/sync", response_model=UserIdentityProfileResponse)
async def synchronize_and_discover_user_role(
    payload: TokenExchangePayload,
    db: AsyncSession = Depends(get_db)
):
    """
    🔐 Hybrid Single-Sign-On Identity Sync Gateway
    Intercepts short-lived cloud provider identity tokens, validates signatures statelessly, 
    auto-provisions new users as students, and returns structural portal redirection targets.
    """
    try:
        decoded_token = firebase_auth.verify_id_token(payload.id_token)
        fb_uid = decoded_token.get("uid")
        fb_email = decoded_token.get("email") or decoded_token.get("claims", {}).get("email")
        fb_name = decoded_token.get("name", fb_email.split("@")[0] if fb_email else "Campus User")
        
    except Exception as token_err:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Identity verification failed. Secure token rejected: {str(token_err)}"
        )

    try:
        user_query = select(User).where((User.firebase_uid == fb_uid) | (User.email == fb_email))
        query_result = await db.execute(user_query)
        existing_user = query_result.scalar_one_or_none()

        if not existing_user:
            if not fb_email:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Identity provider token configuration error: Email attribute missing."
                )
            existing_user = User(
                email=fb_email,
                hashed_password="OAUTH_EXTERNAL_MANAGED_IDENTITY",  
                name=fb_name,
                role="student",  
                username=None,   
                firebase_uid=fb_uid,
                is_active=True
            )
            db.add(existing_user)
            await db.commit()
            await db.refresh(existing_user)
            print(f"👤 [IDENTITY AUTO-PROVISIONED] Created profile row for {fb_email} as 'student'.")
            
        elif not existing_user.firebase_uid:
            existing_user.firebase_uid = fb_uid
            db.add(existing_user)
            await db.commit()
            await db.refresh(existing_user)

        if not existing_user.is_active:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="This campus account infrastructure profile has been administratively deactivated."
            )

        redirect_map = {
            "admin": "/admin/dashboard",
            "helpdesk": "/admin/dashboard",
            "faculty": "/admin/dashboard",
            "student": "/student/chat"
        }
        target_route = redirect_map.get(existing_user.role, "/student/chat")

        return {
            "uid": existing_user.firebase_uid,
            "email": existing_user.email,
            "name": existing_user.name,
            "role": existing_user.role,
            "redirect_target": target_route,
            "is_active": existing_user.is_active
        }

    except HTTPException:
        raise
    except Exception as system_fault:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal database mapping fault during synchronization: {str(system_fault)}"
        )


# ==============================================================================
# 🏢 ENDPOINT 2: SECURE USERNAME/PASSWORD ADMINISTRATIVE LOGIN GATEWAY
# ==============================================================================
@router.post("/admin-login", response_model=AdminLoginResponse)
async def administrative_credentials_login(
    payload: AdminLoginPayload,
    db: AsyncSession = Depends(get_db)
):
    """
    🔐 Hardened Administrative Entrance Gateway
    Accepts both unique alphanumeric username strings or institutional email coordinates,
    compares PBKDF2 hashes safely, and mints an isolated custom token response.
    """
    query = select(User).where((User.username == payload.username) | (User.email == payload.username))
    result = await db.execute(query)
    admin_user = result.scalar_one_or_none()

    if not admin_user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Access Denied: Invalid administrative credentials configuration."
        )

    if not verify_password(payload.password, admin_user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Access Denied: Invalid administrative credentials configuration."
        )

    if not admin_user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This administrative workspace context profile has been deactivated."
        )

    if admin_user.role not in ["admin", "helpdesk", "faculty"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Security Violation: Insufficient role credentials clearance mapping."
        )

    try:
        developer_claims = {
            "email": admin_user.email,
            "role": admin_user.role
        }
        custom_token = firebase_auth.create_custom_token(admin_user.firebase_uid, developer_claims)
        custom_token_str = custom_token.decode("utf-8") if isinstance(custom_token, bytes) else custom_token
    except Exception as token_err:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Identity pipeline critical error: Failed to mint session context: {str(token_err)}"
        )

    redirect_map = {
        "admin": "/admin/dashboard",
        "helpdesk": "/admin/dashboard",
        "faculty": "/admin/dashboard"
    }

    return {
        "uid": admin_user.firebase_uid,
        "email": admin_user.email,
        "name": admin_user.name,
        "role": admin_user.role,
        "custom_token": custom_token_str,
        "redirect_target": redirect_map.get(admin_user.role, "/admin/dashboard")
    }


# ==============================================================================
# ➕ ENDPOINT 3: ATOMIC ADMINISTRATIVE ACCOUNT PROVISIONING (GHOST ROW REMEDIED)
# ==============================================================================
@router.post("/create-admin")
async def create_new_administrative_user(
    payload: dict,  # 👑 FLEXIBLE DICTIONARY: Maps parameters adaptively to handle variable full_name/fullName parameters safely
    current_admin: User = Depends(verify_admin_clearance),  # 🛡️ Received clean structured User object
    db: AsyncSession = Depends(get_db)
):
    """
    👑 Distributed Transaction Provisioning Core
    Safely registers admin operators across Firebase and local engines.
    Atomic verification pipeline completely prevents ghost rows or double-mapping bugs on password rules failure.
    """
    # Extract keys safely to bridge variations across frontends
    full_name = payload.get("full_name", payload.get("fullName", payload.get("adminFullName", ""))).strip()
    email_address = payload.get("email", payload.get("adminEmail", "")).strip()
    username_text = payload.get("username", payload.get("adminUsername", "")).strip()
    raw_password = payload.get("password", payload.get("adminPassword", ""))

    if not full_name or not email_address or not username_text or not raw_password:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Input Validation Error: Full Name, Institutional Email, Username, and Password are required."
        )

    # 1. Enforcement Check: Validate password length bounds before running any updates
    if len(raw_password) < 6:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Firebase Policy Fault: Password string must consist of at least 6 characters."
        )

    # Enforce strict alphanumeric regex formatting rules on the username input
    username_regex = r"^[a-z][a-z0-9_.]{3,19}$"
    if not re.match(username_regex, username_text):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Format Validation Failed: Usernames must start with a lowercase letter, contain only lowercase letters, digits, underscores, or periods, and be 4 to 20 characters long."
        )

    # 2. Local Duplicate Pre-Check: Scan relational tables before processing cloud allocations
    username_check = await db.execute(select(User).where(User.username == username_text))
    if username_check.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"The administrative username '{username_text}' is already allocated inside system records."
        )

    email_check = await db.execute(select(User).where(User.email == email_address))
    if email_check.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"The institutional address '{email_address}' is already mapped to an active profile."
        )

    # 3. Cloud Provider Isolation: Attempt remote account allocation first
    firebase_uid_token = None
    try:
        fb_user = firebase_auth.create_user(
            email=email_address,
            password=raw_password,
            display_name=full_name,
            disabled=False
        )
        firebase_uid_token = fb_user.uid
        
        # Inject custom user claims for administrative role matching
        firebase_auth.set_custom_user_claims(firebase_uid_token, {"role": "admin"})
        
    except Exception as cloud_err:
        print(f"❌ [FIREBASE AUTH REGJECTION] Cloud provider blocked account deployment: {str(cloud_err)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Identity Provider Error: {str(cloud_err)}"
        )

    # 4. Local Persistence Phase: Commit record data rows safely to local disk files
    try:
        new_admin = User(
            email=email_address,
            username=username_text,
            name=full_name,
            role="admin",
            firebase_uid=firebase_uid_token,
            is_active=True,
            hashed_password=hash_password(raw_password)
        )
        db.add(new_admin)
        
        # Log entry context directly into system timelines
        try:
            audit_query = text("""
                INSERT INTO chat_audit_logs (user_query, ai_response, latency_seconds, estimated_tokens, is_safe, triggered_rules)
                VALUES (:user_query, :ai_response, :latency_seconds, :estimated_tokens, :is_safe, :triggered_rules)
            """)
            await db.execute(audit_query, {
                "user_query": "ADMIN_PROVISION_OPERATOR",
                "ai_response": f"Successfully initialized administrative profile for operator username '{username_text}' ({email_address}).",
                "latency_seconds": 0.0,
                "estimated_tokens": 0,
                "is_safe": True,
                "triggered_rules": "None"
            })
        except Exception:
            pass

        await db.commit()
        # 👑 FIXED: Standardized dot lookups (`current_admin.email`) to eliminate the AttributeError 500 crash!
        print(f"👑 [ADMIN PROVISIONED] New operator '{username_text}' generated successfully by supervisor {current_admin.email}.")
        return {
            "success": True, 
            "message": f"Administrative operator profile '{username_text}' successfully registered."
        }
        
    except Exception as db_err:
        await db.rollback()
        print(f"❌ [DB WRITE FAIL] Relational commit failed. Processing cloud compensation fallback... {str(db_err)}")
        
        # 👑 AUTOMATED COMPENSATION ROLLBACK HOOK
        # If local database persistence breaks, delete the user from Firebase
        # to ensure cloud states and local states stay perfectly synchronized.
        if firebase_uid_token:
            try:
                firebase_auth.delete_user(firebase_uid_token)
                print(f"🧹 [CLEANUP SUCCESS] Erased orphaned cloud profile UID: {firebase_uid_token}")
            except Exception as rollback_fault:
                print(f"⚠️ Compensation warning: Cloud user cleanup encountered an issue: {rollback_fault}")

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Relational persistent storage write block failed: {str(db_err)}"
        )


# ==============================================================================
# 🔼 ENDPOINT 4: ADMINISTRATIVE ROLE PROMOTION ELEVATION
# ==============================================================================
@router.post("/promote", status_code=status.HTTP_200_OK)
async def elevate_user_access_clearance(
    payload: PromoteUserPayload,
    current_admin: User = Depends(verify_admin_clearance),  # 👑 FIXED: Swapped signature to receive standard User class
    db: AsyncSession = Depends(get_db)
):
    """
    🔼 Administrative Access Escalation Endpoint
    Allows authorized administrators to update any student's role profile rows 
    to 'admin' status instantly via structural target parameter inputs.
    """
    if payload.target_role not in ["admin", "student", "helpdesk", "faculty"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Target promotion value '{payload.target_role}' is not a recognized campus role archetype."
        )

    # Search for the target user profile record by email address
    user_lookup = select(User).where(User.email == payload.target_email)
    lookup_result = await db.execute(user_lookup)
    target_user = lookup_result.scalar_one_or_none()

    if not target_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Operation aborted: No user profile row exists matching address '{payload.target_email}'."
        )

    # 👑 FIXED: Dot lookup notation (`current_admin.email`) keeps role comparisons safe from crashes
    if target_user.email == current_admin.email and payload.target_role != "admin":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Security Violations: An administrator cannot strip away their own structural clearance codes."
        )

    try:
        old_role = target_user.role
        target_user.role = payload.target_role
        
        # Synchronize custom custom user claims over Firebase cloud records as well
        if target_user.firebase_uid:
            try:
                firebase_auth.set_custom_user_claims(target_user.firebase_uid, {"role": payload.target_role})
            except Exception as claims_err:
                print(f"⚠️ Firebase claims sync delayed: {claims_err}")

        db.add(target_user)
        await db.commit()
        
        print(f"👑 [ACCESS UPGRADED] {target_user.email} changed roles from '{old_role}' to '{payload.target_role}' by admin operator {current_admin.email}.")
        
        return {
            "success": True,
            "message": "Account profile authorization updated completely.",
            "target_user_email": target_user.email,
            "previous_clearance": old_role,
            "assigned_clearance": target_user.role,
            "authorizing_operator": current_admin.email
        }

    except Exception as write_fault:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to modify target authorization parameter settings: {str(write_fault)}"
        )